import { PresetPalette } from '../types/palette';

export const PRESET_PALETTES: PresetPalette[] = [
  // --- VIRIDIS FAMILY ---
  {
    id: 'viridis',
    name: 'Viridis',
    category: 'viridis',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#440154', '#482878', '#3E4A89', '#31688E', '#26828E', '#1F9E89', '#35B779', '#6DCD59', '#B4DE2C', '#FDE725'],
    description: 'Perceptually uniform, robust to color blindness, prints well in grayscale.',
    rScaleColor: 'scale_color_viridis_d(option = "viridis")',
    rScaleFill: 'scale_fill_viridis_d(option = "viridis")',
  },
  {
    id: 'magma',
    name: 'Magma',
    category: 'viridis',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#000004', '#180F3E', '#450F5F', '#721F81', '#9F2F7F', '#CD4071', '#F1605D', '#FD9567', '#FEC98D', '#FCFDBF'],
    description: 'Dark purple to bright yellow, optimized for low to high contrast.',
    rScaleColor: 'scale_color_viridis_d(option = "magma")',
    rScaleFill: 'scale_fill_viridis_d(option = "magma")',
  },
  {
    id: 'inferno',
    name: 'Inferno',
    category: 'viridis',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#000004', '#160B39', '#420A68', '#6A176E', '#932667', '#BA3655', '#DD513A', '#F37819', '#FCA50A', '#FCFFA4'],
    description: 'Fiery progression from black to yellow through deep purples and warm reds.',
    rScaleColor: 'scale_color_viridis_d(option = "inferno")',
    rScaleFill: 'scale_fill_viridis_d(option = "inferno")',
  },
  {
    id: 'plasma',
    name: 'Plasma',
    category: 'viridis',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#0D0887', '#3E049C', '#6300A7', '#8707A6', '#A62098', '#C03A83', '#D6546E', '#E76F5A', '#F58E46', '#F0F921'],
    description: 'Vibrant blue to red to yellow sequential scale.',
    rScaleColor: 'scale_color_viridis_d(option = "plasma")',
    rScaleFill: 'scale_fill_viridis_d(option = "plasma")',
  },
  {
    id: 'cividis',
    name: 'Cividis',
    category: 'viridis',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#00204D', '#1B315A', '#334467', '#4A5774', '#616A82', '#797F8F', '#92949D', '#ADACAC', '#CAC5BC', '#EAE5CC'],
    description: 'Specifically engineered to be perceptually uniform for both red-green CVD and normal vision.',
    rScaleColor: 'scale_color_viridis_d(option = "cividis")',
    rScaleFill: 'scale_fill_viridis_d(option = "cividis")',
  },
  {
    id: 'mako',
    name: 'Mako',
    category: 'viridis',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#0B0405', '#1B1935', '#243354', '#2C4F6E', '#326E86', '#388F9A', '#45B09E', '#67D095', '#A3E994', '#DEF5E5'],
    description: 'Deep ocean dark to cyan-mint progression.',
    rScaleColor: 'scale_color_viridis_d(option = "mako")',
    rScaleFill: 'scale_fill_viridis_d(option = "mako")',
  },

  // --- BASE R ACCESSIBLE PALETTES ---
  {
    id: 'okabe_ito',
    name: 'Okabe-Ito',
    category: 'base_r',
    type: 'qualitative',
    isColorblindSafe: true,
    colors: ['#E69F00', '#56B4E9', '#009E73', '#F0E442', '#0072B2', '#D55E00', '#CC79A7', '#000000'],
    description: 'Gold-standard colorblind-friendly categorical palette (Nature Methods recommendation).',
    rScaleColor: 'scale_color_discrete(type = palette.colors(palette = "Okabe-Ito"))',
    rScaleFill: 'scale_fill_discrete(type = palette.colors(palette = "Okabe-Ito"))',
  },
  {
    id: 'tableau10',
    name: 'Tableau 10',
    category: 'base_r',
    type: 'qualitative',
    isColorblindSafe: true,
    colors: ['#4E79A7', '#F28E2B', '#E15759', '#76B7B2', '#59A14F', '#EDC948', '#B07AA1', '#FF9DA7', '#9C755F', '#BAB0AC'],
    description: 'Tableau 10 accessible qualitative palette available in base R palette.colors().',
    rScaleColor: 'scale_color_discrete(type = palette.colors(palette = "Tableau 10"))',
    rScaleFill: 'scale_fill_discrete(type = palette.colors(palette = "Tableau 10"))',
  },

  // --- RCOLORBREWER: QUALITATIVE ---
  {
    id: 'brewer_dark2',
    name: 'Dark2',
    category: 'brewer_qual',
    type: 'qualitative',
    isColorblindSafe: true,
    colors: ['#1B9E77', '#D95F02', '#7570B3', '#E7298A', '#66A61E', '#E6AB02', '#A6761D', '#666666'],
    description: 'High-contrast qualitative palette from Cynthia Brewer, robust to CVD.',
    rScaleColor: 'scale_color_brewer(palette = "Dark2")',
    rScaleFill: 'scale_fill_brewer(palette = "Dark2")',
  },
  {
    id: 'brewer_set2',
    name: 'Set2',
    category: 'brewer_qual',
    type: 'qualitative',
    isColorblindSafe: true,
    colors: ['#66C2A5', '#FC8D62', '#8DA0CB', '#E78AC3', '#A6D854', '#FFD92F', '#E5C494', '#B3B3B3'],
    description: 'Soft, pleasant qualitative tones with moderate contrast.',
    rScaleColor: 'scale_color_brewer(palette = "Set2")',
    rScaleFill: 'scale_fill_brewer(palette = "Set2")',
  },
  {
    id: 'brewer_set1',
    name: 'Set1',
    category: 'brewer_qual',
    type: 'qualitative',
    isColorblindSafe: false,
    colors: ['#E41A1C', '#377EB8', '#4DAF4A', '#984EA3', '#FF7F00', '#FFFF33', '#A65628', '#F781BF', '#999999'],
    description: 'High-energy primary/secondary qualitative colors.',
    rScaleColor: 'scale_color_brewer(palette = "Set1")',
    rScaleFill: 'scale_fill_brewer(palette = "Set1")',
  },
  {
    id: 'brewer_paired',
    name: 'Paired',
    category: 'brewer_qual',
    type: 'qualitative',
    isColorblindSafe: false,
    colors: ['#A6CEE3', '#1F78B4', '#B2DF8A', '#33A02C', '#FB9A99', '#E31A1C', '#FDBF6F', '#FF7F00', '#CAB2D6', '#6A3D9A', '#FFFF99', '#B15928'],
    description: 'Light and dark pairs designed for related sub-categories.',
    rScaleColor: 'scale_color_brewer(palette = "Paired")',
    rScaleFill: 'scale_fill_brewer(palette = "Paired")',
  },
  {
    id: 'brewer_set3',
    name: 'Set3',
    category: 'brewer_qual',
    type: 'qualitative',
    isColorblindSafe: false,
    colors: ['#8DD3C7', '#FFFFB3', '#BEBADA', '#FB8072', '#80B1D3', '#FDB462', '#B3DE69', '#FCCDE5', '#D9D9D9', '#BC80BD', '#CCEBC5', '#FFED6F'],
    description: '12 soft pastel tones for complex qualitative factors.',
    rScaleColor: 'scale_color_brewer(palette = "Set3")',
    rScaleFill: 'scale_fill_brewer(palette = "Set3")',
  },

  // --- RCOLORBREWER: SEQUENTIAL ---
  {
    id: 'brewer_blues',
    name: 'Blues',
    category: 'brewer_seq',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#F7FBFF', '#DEEBF7', '#C6DBEF', '#9ECAE1', '#6BAED6', '#4292C6', '#2171B5', '#08519C', '#08306B'],
    description: 'Monochromatic blue sequential ramp. Safe for CVD.',
    rScaleColor: 'scale_color_brewer(palette = "Blues")',
    rScaleFill: 'scale_fill_brewer(palette = "Blues")',
  },
  {
    id: 'brewer_greens',
    name: 'Greens',
    category: 'brewer_seq',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#F7FCF5', '#E5F5E0', '#C7E9C0', '#A1D99B', '#74C476', '#41AB5D', '#238B45', '#006D2C', '#00441B'],
    description: 'Monochromatic green sequential ramp. Safe for CVD.',
    rScaleColor: 'scale_color_brewer(palette = "Greens")',
    rScaleFill: 'scale_fill_brewer(palette = "Greens")',
  },
  {
    id: 'brewer_purples',
    name: 'Purples',
    category: 'brewer_seq',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#FCFBFD', '#EFEDF5', '#DADAEB', '#BCBDDC', '#9E9AC8', '#807DBA', '#6A51A3', '#54278F', '#3F007D'],
    description: 'Monochromatic purple sequential ramp.',
    rScaleColor: 'scale_color_brewer(palette = "Purples")',
    rScaleFill: 'scale_fill_brewer(palette = "Purples")',
  },
  {
    id: 'brewer_greys',
    name: 'Greys',
    category: 'brewer_seq',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#FFFFFF', '#F0F0F0', '#D9D9D9', '#BDBDBD', '#969696', '#737373', '#525252', '#252525', '#000000'],
    description: 'Monochromatic grayscale sequential ramp.',
    rScaleColor: 'scale_color_brewer(palette = "Greys")',
    rScaleFill: 'scale_fill_brewer(palette = "Greys")',
  },
  {
    id: 'brewer_oranges',
    name: 'Oranges',
    category: 'brewer_seq',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#FFF5EB', '#FEE6CE', '#FDD0A2', '#FDAE6B', '#FD8D3C', '#F16913', '#D94801', '#A63603', '#7F2704'],
    description: 'Warm monochromatic orange sequential ramp.',
    rScaleColor: 'scale_color_brewer(palette = "Oranges")',
    rScaleFill: 'scale_fill_brewer(palette = "Oranges")',
  },
  {
    id: 'brewer_ylorrd',
    name: 'YlOrRd',
    category: 'brewer_seq',
    type: 'sequential',
    isColorblindSafe: false,
    colors: ['#FFFFCC', '#FFEDA0', '#FED976', '#FEB24C', '#FD8D3C', '#FC4E2A', '#E31A1C', '#BD0026', '#800026'],
    description: 'Yellow to Orange to Red sequential heatmap palette.',
    rScaleColor: 'scale_color_brewer(palette = "YlOrRd")',
    rScaleFill: 'scale_fill_brewer(palette = "YlOrRd")',
  },

  // --- RCOLORBREWER: DIVERGING ---
  {
    id: 'brewer_rdbu',
    name: 'RdBu',
    category: 'brewer_div',
    type: 'diverging',
    isColorblindSafe: true,
    colors: ['#67001F', '#B2182B', '#D6604D', '#F4A582', '#FDDBC7', '#FFFFFF', '#D1E5F0', '#92C5DE', '#4393C3', '#2166AC', '#053061'],
    description: 'Red to Blue diverging scale with neutral white center. Highly recommended for correlations.',
    rScaleColor: 'scale_color_brewer(palette = "RdBu")',
    rScaleFill: 'scale_fill_brewer(palette = "RdBu")',
  },
  {
    id: 'brewer_piyg',
    name: 'PiYG',
    category: 'brewer_div',
    type: 'diverging',
    isColorblindSafe: true,
    colors: ['#8E0152', '#C51B7D', '#DE77AE', '#F1B6DA', '#FDE0EF', '#F7F7F7', '#E6F5D0', '#B8E186', '#7FBC41', '#4D9221', '#276419'],
    description: 'Pink to Yellow-Green diverging scale with strong contrast.',
    rScaleColor: 'scale_color_brewer(palette = "PiYG")',
    rScaleFill: 'scale_fill_brewer(palette = "PiYG")',
  },
  {
    id: 'brewer_prgn',
    name: 'PRGn',
    category: 'brewer_div',
    type: 'diverging',
    isColorblindSafe: true,
    colors: ['#40004B', '#762A83', '#9970AB', '#C2A5CF', '#E7D4E8', '#F7F7F7', '#D9F0D3', '#A6DBA0', '#5AAE61', '#1B7837', '#00441B'],
    description: 'Purple to Green diverging scale. Excellent CVD distinction.',
    rScaleColor: 'scale_color_brewer(palette = "PRGn")',
    rScaleFill: 'scale_fill_brewer(palette = "PRGn")',
  },
  {
    id: 'brewer_brbg',
    name: 'BrBG',
    category: 'brewer_div',
    type: 'diverging',
    isColorblindSafe: true,
    colors: ['#543005', '#8C510A', '#BF812D', '#DFC27D', '#F6E8C3', '#F5F5F5', '#C7EAE5', '#80CDC1', '#35978F', '#01665E', '#003C30'],
    description: 'Brown to Blue-Green earth tone diverging scale.',
    rScaleColor: 'scale_color_brewer(palette = "BrBG")',
    rScaleFill: 'scale_fill_brewer(palette = "BrBG")',
  },
  {
    id: 'brewer_spectral',
    name: 'Spectral',
    category: 'brewer_div',
    type: 'diverging',
    isColorblindSafe: false,
    colors: ['#9E0142', '#D53E4F', '#F46D43', '#FDAE61', '#FEE08B', '#FFFFBF', '#E6F598', '#ABDDA4', '#66C2A5', '#3288BD', '#5E4FA2'],
    description: 'Multi-hue rainbow-like diverging palette with light center.',
    rScaleColor: 'scale_color_brewer(palette = "Spectral")',
    rScaleFill: 'scale_fill_brewer(palette = "Spectral")',
  },
];
