import { PresetPalette } from '../types/palette';

export const PRESET_PALETTES: PresetPalette[] = [
  // --- VIRIDIS FAMILY ---
  {
    id: 'viridis',
    name: 'Viridis',
    package: 'viridis',
    category: 'viridis',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#440154', '#482878', '#3E4A89', '#31688E', '#26828E', '#1F9E89', '#35B779', '#6DCD59', '#B4DE2C', '#FDE725'],
    description: 'Perceptually uniform, robust to color blindness, prints well in grayscale.',
    rScaleColor: 'scale_color_viridis_d(option = "viridis")',
    rScaleFill: 'scale_fill_viridis_d(option = "viridis")',
  },
  {
    id: 'magma',
    name: 'Magma',
    package: 'viridis',
    category: 'viridis',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#000004', '#180F3E', '#450F5F', '#721F81', '#9F2F7F', '#CD4071', '#F1605D', '#FD9567', '#FEC98D', '#FCFDBF'],
    description: 'Dark purple to bright yellow, optimized for low to high contrast.',
    rScaleColor: 'scale_color_viridis_d(option = "magma")',
    rScaleFill: 'scale_fill_viridis_d(option = "magma")',
  },
  {
    id: 'inferno',
    name: 'Inferno',
    package: 'viridis',
    category: 'viridis',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#000004', '#160B39', '#420A68', '#6A176E', '#932667', '#BA3655', '#DD513A', '#F37819', '#FCA50A', '#FCFFA4'],
    description: 'Fiery progression from black to yellow through deep purples and warm reds.',
    rScaleColor: 'scale_color_viridis_d(option = "inferno")',
    rScaleFill: 'scale_fill_viridis_d(option = "inferno")',
  },
  {
    id: 'plasma',
    name: 'Plasma',
    package: 'viridis',
    category: 'viridis',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#0D0887', '#3E049C', '#6300A7', '#8707A6', '#A62098', '#C03A83', '#D6546E', '#E76F5A', '#F58E46', '#F0F921'],
    description: 'Vibrant blue to red to yellow sequential scale.',
    rScaleColor: 'scale_color_viridis_d(option = "plasma")',
    rScaleFill: 'scale_fill_viridis_d(option = "plasma")',
  },
  {
    id: 'cividis',
    name: 'Cividis',
    package: 'viridis',
    category: 'viridis',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#00204D', '#1B315A', '#334467', '#4A5774', '#616A82', '#797F8F', '#92949D', '#ADACAC', '#CAC5BC', '#EAE5CC'],
    description: 'Specifically engineered to be perceptually uniform for both red-green CVD and normal vision.',
    rScaleColor: 'scale_color_viridis_d(option = "cividis")',
    rScaleFill: 'scale_fill_viridis_d(option = "cividis")',
  },
  {
    id: 'mako',
    name: 'Mako',
    package: 'viridis',
    category: 'viridis',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#0B0405', '#1B1935', '#243354', '#2C4F6E', '#326E86', '#388F9A', '#45B09E', '#67D095', '#A3E994', '#DEF5E5'],
    description: 'Deep ocean dark to cyan-mint progression.',
    rScaleColor: 'scale_color_viridis_d(option = "mako")',
    rScaleFill: 'scale_fill_viridis_d(option = "mako")',
  },

  // --- ACCESSIBLE BENCHMARKS ---
  {
    id: 'okabe_ito',
    name: 'Okabe-Ito',
    package: 'colorblindr',
    category: 'accessible',
    type: 'qualitative',
    isColorblindSafe: true,
    colors: ['#E69F00', '#56B4E9', '#009E73', '#F0E442', '#0072B2', '#D55E00', '#CC79A7', '#000000'],
    description: 'Gold-standard colorblind-friendly categorical palette (Nature Methods recommendation).',
    rScaleColor: 'scale_color_manual(values = c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000"))',
    rScaleFill: 'scale_fill_manual(values = c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000"))',
  },
  {
    id: 'tol_bright',
    name: 'Paul Tol (Bright)',
    package: 'khroma',
    category: 'accessible',
    type: 'qualitative',
    isColorblindSafe: true,
    colors: ['#4477AA', '#66CCEE', '#228833', '#CCBB44', '#EE6677', '#AA3377', '#BBBBBB'],
    description: 'Distinct qualitative colors designed by Paul Tol for scientific publication.',
    rScaleColor: 'scale_color_manual(values = c("#4477AA", "#66CCEE", "#228833", "#CCBB44", "#EE6677", "#AA3377", "#BBBBBB"))',
    rScaleFill: 'scale_fill_manual(values = c("#4477AA", "#66CCEE", "#228833", "#CCBB44", "#EE6677", "#AA3377", "#BBBBBB"))',
  },
  {
    id: 'tol_muted',
    name: 'Paul Tol (Muted)',
    package: 'khroma',
    category: 'accessible',
    type: 'qualitative',
    isColorblindSafe: true,
    colors: ['#CC6677', '#332288', '#DDCC77', '#117733', '#88CCEE', '#882255', '#44AA99', '#999933', '#AA4499'],
    description: 'Muted categorical palette with strong accessibility across all dichromatic vision types.',
    rScaleColor: 'scale_color_manual(values = c("#CC6677", "#332288", "#DDCC77", "#117733", "#88CCEE", "#882255", "#44AA99", "#999933", "#AA4499"))',
    rScaleFill: 'scale_fill_manual(values = c("#CC6677", "#332288", "#DDCC77", "#117733", "#88CCEE", "#882255", "#44AA99", "#999933", "#AA4499"))',
  },

  // --- RCOLORBREWER: QUALITATIVE ---
  {
    id: 'brewer_dark2',
    name: 'Dark2',
    package: 'RColorBrewer',
    category: 'brewer_qual',
    type: 'qualitative',
    isColorblindSafe: true,
    colors: ['#1B9E77', '#D95F02', '#7570B3', '#E7298A', '#66A61E', '#E6AB02', '#A6761D', '#666666'],
    description: 'High-contrast qualitative palette from Cynthia Brewer, relatively robust to CVD.',
    rScaleColor: 'scale_color_brewer(palette = "Dark2")',
    rScaleFill: 'scale_fill_brewer(palette = "Dark2")',
  },
  {
    id: 'brewer_set2',
    name: 'Set2',
    package: 'RColorBrewer',
    category: 'brewer_qual',
    type: 'qualitative',
    isColorblindSafe: true,
    colors: ['#66C2A5', '#FC8D62', '#8DA0CB', '#E78AC3', '#A6D854', '#FFD92F', '#E5C494', '#B3B3B3'],
    description: 'Soft, pleasant qualitative tones with moderate contrast.',
    rScaleColor: 'scale_color_brewer(palette = "Set2")',
    rScaleFill: 'scale_fill_brewer(palette = "Set2")',
  },
  {
    id: 'brewer_set1',
    name: 'Set1',
    package: 'RColorBrewer',
    category: 'brewer_qual',
    type: 'qualitative',
    isColorblindSafe: false,
    colors: ['#E41A1C', '#377EB8', '#4DAF4A', '#984EA3', '#FF7F00', '#FFFF33', '#A65628', '#F781BF', '#999999'],
    description: 'High-energy primary/secondary qualitative colors (caution: red/green pairing).',
    rScaleColor: 'scale_color_brewer(palette = "Set1")',
    rScaleFill: 'scale_fill_brewer(palette = "Set1")',
  },
  {
    id: 'brewer_paired',
    name: 'Paired',
    package: 'RColorBrewer',
    category: 'brewer_qual',
    type: 'qualitative',
    isColorblindSafe: false,
    colors: ['#A6CEE3', '#1F78B4', '#B2DF8A', '#33A02C', '#FB9A99', '#E31A1C', '#FDBF6F', '#FF7F00', '#CAB2D6', '#6A3D9A', '#FFFF99', '#B15928'],
    description: 'Light and dark pairs designed for related sub-categories.',
    rScaleColor: 'scale_color_brewer(palette = "Paired")',
    rScaleFill: 'scale_fill_brewer(palette = "Paired")',
  },

  // --- RCOLORBREWER: SEQUENTIAL ---
  {
    id: 'brewer_blues',
    name: 'Blues',
    package: 'RColorBrewer',
    category: 'brewer_seq',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#F7FBFF', '#DEEBF7', '#C6DBEF', '#9ECAE1', '#6BAED6', '#4292C6', '#2171B5', '#08519C', '#08306B'],
    description: 'Monochromatic blue sequential ramp. Safe for CVD.',
    rScaleColor: 'scale_color_brewer(palette = "Blues")',
    rScaleFill: 'scale_fill_brewer(palette = "Blues")',
  },
  {
    id: 'brewer_ylgnbu',
    name: 'YlGnBu',
    package: 'RColorBrewer',
    category: 'brewer_seq',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#FFFFD9', '#EDF8B1', '#C7E9B4', '#7FCDBB', '#41B6C4', '#1D91C0', '#225EA8', '#253494', '#081D58'],
    description: 'Yellow-Green-Blue multi-hue sequential gradient.',
    rScaleColor: 'scale_color_brewer(palette = "YlGnBu")',
    rScaleFill: 'scale_fill_brewer(palette = "YlGnBu")',
  },
  {
    id: 'brewer_purples',
    name: 'Purples',
    package: 'RColorBrewer',
    category: 'brewer_seq',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#FCFBFD', '#EFEDF5', '#DADAEB', '#BCBDDC', '#9E9AC8', '#807DBA', '#6A51A3', '#54278F', '#3F007D'],
    description: 'Monochromatic purple sequential ramp.',
    rScaleColor: 'scale_color_brewer(palette = "Purples")',
    rScaleFill: 'scale_fill_brewer(palette = "Purples")',
  },
  {
    id: 'brewer_oranges',
    name: 'Oranges',
    package: 'RColorBrewer',
    category: 'brewer_seq',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#FFF5EB', '#FEE6CE', '#FDD0A2', '#FDAE6B', '#FD8D3C', '#F16913', '#D94801', '#A63603', '#7F2704'],
    description: 'Warm monochromatic orange sequential ramp.',
    rScaleColor: 'scale_color_brewer(palette = "Oranges")',
    rScaleFill: 'scale_fill_brewer(palette = "Oranges")',
  },

  // --- RCOLORBREWER: DIVERGING ---
  {
    id: 'brewer_spectral',
    name: 'Spectral',
    package: 'RColorBrewer',
    category: 'brewer_div',
    type: 'diverging',
    isColorblindSafe: false,
    colors: ['#9E0142', '#D53E4F', '#F46D43', '#FDAE61', '#FEE08B', '#FFFFBF', '#E6F598', '#ABDDA4', '#66C2A5', '#3288BD', '#5E4FA2'],
    description: 'Multi-hue rainbow-like diverging palette with light center.',
    rScaleColor: 'scale_color_brewer(palette = "Spectral")',
    rScaleFill: 'scale_fill_brewer(palette = "Spectral")',
  },
  {
    id: 'brewer_rdbu',
    name: 'RdBu',
    package: 'RColorBrewer',
    category: 'brewer_div',
    type: 'diverging',
    isColorblindSafe: true,
    colors: ['#67001F', '#B2182B', '#D6604D', '#F4A582', '#FDDBC7', '#FFFFFF', '#D1E5F0', '#92C5DE', '#4393C3', '#2166AC', '#053061'],
    description: 'Red to Blue diverging scale with white neutral midpoint. Widely recommended for correlations.',
    rScaleColor: 'scale_color_brewer(palette = "RdBu")',
    rScaleFill: 'scale_fill_brewer(palette = "RdBu")',
  },
  {
    id: 'brewer_prgn',
    name: 'PRGn',
    package: 'RColorBrewer',
    category: 'brewer_div',
    type: 'diverging',
    isColorblindSafe: true,
    colors: ['#40004B', '#762A83', '#9970AB', '#C2A5CF', '#E7D4E8', '#F7F7F7', '#D9F0D3', '#A6DBA0', '#5AAE61', '#1B7837', '#00441B'],
    description: 'Purple to Green diverging scale. Excellent CVD distinction.',
    rScaleColor: 'scale_color_brewer(palette = "PRGn")',
    rScaleFill: 'scale_fill_brewer(palette = "PRGn")',
  },

  // --- GGPLOT2 DEFAULTS ---
  {
    id: 'ggplot2_hue',
    name: 'ggplot2 Default (Hue)',
    package: 'ggplot2',
    category: 'ggplot2',
    type: 'qualitative',
    isColorblindSafe: false,
    colors: ['#F8766D', '#B79F00', '#00BA38', '#00BFC4', '#619CFF', '#F564E3'],
    description: 'Evenly spaced hues on the HCL color wheel used by ggplot2 scale_color_hue().',
    rScaleColor: 'scale_color_hue()',
    rScaleFill: 'scale_fill_hue()',
  },
  {
    id: 'ggplot2_grey',
    name: 'ggplot2 Grey',
    package: 'ggplot2',
    category: 'ggplot2',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#333333', '#555555', '#777777', '#999999', '#BBBBBB', '#DDDDDD'],
    description: 'Sequential grayscale from ggplot2 scale_color_grey().',
    rScaleColor: 'scale_color_grey()',
    rScaleFill: 'scale_fill_grey()',
  },

  // --- BASE R ---
  {
    id: 'base_rainbow',
    name: 'rainbow()',
    package: 'grDevices',
    category: 'base_r',
    type: 'qualitative',
    isColorblindSafe: false,
    colors: ['#FF0000', '#FFAA00', '#55FF00', '#00FFAA', '#0055FF', '#AA00FF'],
    description: 'Legacy base R rainbow() palette. Caution: non-uniform luminance.',
    rScaleColor: 'scale_color_manual(values = rainbow(6))',
    rScaleFill: 'scale_fill_manual(values = rainbow(6))',
  },
  {
    id: 'base_heat',
    name: 'heat.colors()',
    package: 'grDevices',
    category: 'base_r',
    type: 'sequential',
    isColorblindSafe: true,
    colors: ['#FF0000', '#FF5500', '#FFAA00', '#FFFF00', '#FFFF80', '#FFFFFF'],
    description: 'Base R heat.colors() red to white gradient.',
    rScaleColor: 'scale_color_manual(values = heat.colors(6))',
    rScaleFill: 'scale_fill_manual(values = heat.colors(6))',
  },
  {
    id: 'base_terrain',
    name: 'terrain.colors()',
    package: 'grDevices',
    category: 'base_r',
    type: 'sequential',
    isColorblindSafe: false,
    colors: ['#00A600', '#63C600', '#E6E600', '#EAB64E', '#C2834E', '#FFFFFF'],
    description: 'Base R topographic elevation palette (green to yellow to brown to snow white).',
    rScaleColor: 'scale_color_manual(values = terrain.colors(6))',
    rScaleFill: 'scale_fill_manual(values = terrain.colors(6))',
  },
  {
    id: 'base_topo',
    name: 'topo.colors()',
    package: 'grDevices',
    category: 'base_r',
    type: 'sequential',
    isColorblindSafe: false,
    colors: ['#4C00FF', '#004CFF', '#00E5FF', '#00FF4D', '#FFFF00', '#FFE5CC'],
    description: 'Base R topo.colors() blue to cyan to green to yellow.',
    rScaleColor: 'scale_color_manual(values = topo.colors(6))',
    rScaleFill: 'scale_fill_manual(values = topo.colors(6))',
  },
];
