export interface RPackageFile {
  path: string;
  description: string;
  content: string;
}

export const R_PACKAGE_FILES: RPackageFile[] = [
  {
    path: 'DESCRIPTION',
    description: 'R Package Metadata and CRAN/GitHub dependencies',
    content: `Package: ColorLab
Title: Interactive Color and Shape Palette Designer for ggplot2
Version: 0.2.0
Authors@R: person("Boaz", "Rosenberg", email = "boazrsnbrg@gmail.com", role = c("aut", "cre"))
Description: An interactive, modern color palette and ggplot2 shape designer
    that runs seamlessly in the RStudio Viewer Pane without blocking the R console.
    Provides custom color ramps, curated presets (Okabe-Ito, ColorBrewer, Viridis),
    gradient interpolation, color-vision deficiency simulation, and instant R code generation.
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.3.1
Imports:
    utils
Suggests:
    httpuv,
    rstudioapi,
    ggplot2,
    RColorBrewer,
    viridis,
    testthat (>= 3.0.0)
URL: https://github.com/BoazRosenberg/ColorLab
BugReports: https://github.com/BoazRosenberg/ColorLab/issues
`,
  },
  {
    path: '.Rbuildignore',
    description: 'Instructs R CMD build to exclude non-R repository files',
    content: `^src$
^node_modules$
^package\\.json$
^package-lock\\.json$
^tsconfig.*\\.json$
^vite\\.config\\.ts$
^\\.env.*$
^metadata\\.json$
^index\\.html$
^\\.git$
^\\.gitignore$
^\\.aistudio.*$
^dist$
`,
  },
  {
    path: 'NAMESPACE',
    description: 'Exported R functions and imported dependencies',
    content: `# Generated by roxygen2: do not edit by hand

export(colorlab)
export(colorlab_stop)
export(ColorLab)
export(run_colorlab)
export(launch_palette_tutorial)
importFrom(utils,browseURL)
`,
  },
  {
    path: 'R/launch.R',
    description: 'Non-blocking launch function for RStudio Viewer Pane with .onAttach auto-launch',
    content: `# Internal environment for background server state
.colorlab_env <- new.env(parent = emptyenv())
.colorlab_env$server <- NULL
.colorlab_env$port <- NULL

#' Automatically launch ColorLab when package is loaded
#' @keywords internal
.onAttach <- function(libname, pkgname) {
  if (interactive()) {
    tryCatch({
      colorlab()
    }, error = function(e) {
      packageStartupMessage("Type colorlab() to open the palette designer in Viewer.")
    })
  }
}

#' Launch ColorLab in RStudio Viewer Pane
#'
#' Opens the interactive ColorLab color palette and shape designer in
#' RStudio's Viewer Pane (or default web browser if outside RStudio).
#' ColorLab runs asynchronously and does not block the R console, so you can
#' continue writing and executing code while ColorLab is open.
#'
#' @param browser Logical. If \\code{TRUE}, opens in the system web browser
#'   instead of the RStudio Viewer pane. Default is \\code{FALSE}.
#' @param port Integer. Preferred TCP port if using a local background HTTP server.
#'   Default selects a random available port.
#'
#' @return Invisibly returns the URL or local path to the running application.
#' @export
#' @examples
#' \\dontrun{
#' library(ColorLab)
#'
#' # Launch in RStudio Viewer
#' colorlab()
#'
#' # Or open in external web browser
#' colorlab(browser = TRUE)
#' }
colorlab <- function(browser = FALSE, port = NULL) {
  app_file <- system.file("app", "index.html", package = "ColorLab")
  if (!nzchar(app_file) || !file.exists(app_file)) {
    app_file <- system.file("dist", "index.html", package = "ColorLab")
  }
  if (!nzchar(app_file) || !file.exists(app_file)) {
    dev_paths <- c(
      file.path(getwd(), "inst", "app", "index.html"),
      file.path(getwd(), "dist", "index.html")
    )
    for (p in dev_paths) {
      if (file.exists(p)) {
        app_file <- p
        break
      }
    }
  }

  if (!nzchar(app_file) || !file.exists(app_file)) {
    stop(
      "ColorLab application bundle not found.\\n",
      "Please reinstall ColorLab: remotes::install_github('BoazRosenberg/ColorLab')",
      call. = FALSE
    )
  }

  viewer <- getOption("viewer")
  use_viewer <- !isTRUE(browser) && !is.null(viewer)

  is_rstudio_server <- nzchar(Sys.getenv("RSTUDIO_HTTP_REFERER")) ||
    nzchar(Sys.getenv("RSTUDIO_SERVER")) ||
    nzchar(Sys.getenv("POSIT_CLOUD"))

  if (requireNamespace("httpuv", quietly = TRUE) && (is_rstudio_server || !is.null(port))) {
    if (is.null(.colorlab_env$server)) {
      if (is.null(port)) {
        port <- sample(3100:8999, 1)
      }
      
      app_handler <- list(
        call = function(req) {
          list(
            status = 200L,
            headers = list(
              "Content-Type" = "text/html; charset=utf-8",
              "Access-Control-Allow-Origin" = "*"
            ),
            body = readBin(app_file, "raw", file.info(app_file)$size)
          )
        }
      )

      tryCatch({
        .colorlab_env$server <- httpuv::startServer("127.0.0.1", port, app_handler)
        .colorlab_env$port <- port
      }, error = function(e) {
        .colorlab_env$server <- NULL
      })
    }

    if (!is.null(.colorlab_env$server)) {
      url <- sprintf("http://127.0.0.1:%d", .colorlab_env$port)
      if (use_viewer) {
        viewer(url)
        message("ColorLab launched in RStudio Viewer.")
      } else {
        utils::browseURL(url)
        message("ColorLab opened in browser (", url, ").")
      }
      return(invisible(url))
    }
  }

  temp_dir <- file.path(tempdir(), "ColorLab")
  if (!dir.exists(temp_dir)) dir.create(temp_dir, recursive = TRUE, showWarnings = FALSE)
  dest_file <- file.path(temp_dir, "index.html")
  file.copy(app_file, dest_file, overwrite = TRUE)

  if (use_viewer) {
    viewer(dest_file)
    message("ColorLab launched in RStudio Viewer.")
  } else {
    utils::browseURL(dest_file)
    message("ColorLab opened in default browser.")
  }

  invisible(dest_file)
}

#' Stop ColorLab Background Server
#'
#' Stops any local background HTTP server started by \\code{colorlab()}.
#'
#' @export
colorlab_stop <- function() {
  if (!is.null(.colorlab_env$server)) {
    tryCatch({
      httpuv::stopServer(.colorlab_env$server)
    }, error = function(e) NULL)
    .colorlab_env$server <- NULL
    .colorlab_env$port <- NULL
    message("ColorLab background server stopped.")
  } else {
    message("No ColorLab background server is currently running.")
  }
  invisible(NULL)
}

#' @rdname colorlab
#' @export
run_colorlab <- function(...) {
  colorlab(...)
}

#' @rdname colorlab
#' @export
ColorLab <- function(...) {
  colorlab(...)
}
`,
  },
  {
    path: 'man/colorlab.Rd',
    description: 'Documentation for colorlab and Viewer Pane integration',
    content: `% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/launch.R
\\name{colorlab}
\\alias{colorlab}
\\alias{colorlab_stop}
\\alias{run_colorlab}
\\alias{ColorLab}
\\title{Launch ColorLab in RStudio Viewer Pane}
\\usage{
colorlab(browser = FALSE, port = NULL)

colorlab_stop()

run_colorlab(...)

ColorLab(...)
}
\\arguments{
\\item{browser}{Logical. If \\code{TRUE}, opens in the default system web browser
instead of RStudio's Viewer pane. Default is \\code{FALSE}.}

\\item{port}{Integer. Preferred TCP port if using a local background HTTP server.
Default selects a random available port.}

\\item{...}{Additional arguments forwarded to \\code{colorlab()}.}
}
\\value{
Invisibly returns the local file path or server URL.
}
\\description{
Opens the interactive ColorLab color palette and ggplot2 shape designer in
RStudio's Viewer Pane (or external web browser). When the package is loaded
via \\code{library(ColorLab)}, it automatically launches into the Viewer pane.
ColorLab runs asynchronously and does not block the R console.
}
\\examples{
\\dontrun{
# Automatically launches on load:
library(ColorLab)

# Or launch explicitly anytime:
colorlab()

# Or open in external browser:
colorlab(browser = TRUE)

# Stop background server if started
colorlab_stop()
}
}
`,
  },
  {
    path: 'README.md',
    description: 'Package documentation and RStudio Viewer Pane instructions',
    content: `# ColorLab 🎨

Interactive Color and Shape Palette Designer for ggplot2 and RStudio.

## Installation

\`\`\`r
# Install from GitHub
remotes::install_github("BoazRosenberg/ColorLab")

# Or with pak
pak::pak("BoazRosenberg/ColorLab")
\`\`\`

## Launching in RStudio

Simply run:

\`\`\`r
library(ColorLab)
\`\`\`

ColorLab automatically launches in your RStudio Viewer Pane upon loading the library!
`,
  },
  {
    path: 'tests/testthat/test-palette.R',
    description: 'Unit tests verifying ColorLab export functions and bundle presence',
    content: `test_that("ColorLab app bundle exists in package", {
  app_file <- system.file("app", "index.html", package = "ColorLab")
  expect_true(nzchar(app_file) || file.exists("inst/app/index.html") || file.exists("dist/index.html"))
})

test_that("colorlab function is exported", {
  expect_true(is.function(colorlab))
  expect_true(is.function(run_colorlab))
  expect_true(is.function(ColorLab))
})
`,
  },
];
