import JSZip from 'jszip';

export interface RPackageFile {
  path: string;
  description: string;
  content: string;
}

export const R_PACKAGE_FILES: RPackageFile[] = [
  {
    path: 'DESCRIPTION',
    description: 'R Package Metadata and CRAN-compliant dependency specification',
    content: `Package: ColorLab
Title: Interactive Color and Shape Palette Designer for ggplot2
Version: 0.1.0
Authors@R: c(
    person("Boaz", "Rosenberg", email = "BoazRsnbrg@gmail.com", role = c("aut", "cre"))
  )
Description: Provides a minimal interactive learnr tutorial designed specifically for the
    narrow dimensions of the RStudio Tutorial Pane. Users can interactively design
    custom color palettes, sample and edge-prune preset palettes, build multi-anchor
    asymmetric interpolated gradients, and configure ggplot2 shape scales with live
    color vision deficiency (CVD) simulation.
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.3.1
Imports:
    learnr (>= 0.11.0),
    shiny (>= 1.8.0),
    bslib (>= 0.7.0),
    ggplot2 (>= 3.5.0),
    colorspace (>= 2.1-0)
Suggests:
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
VignetteBuilder: knitr
URL: https://github.com/BoazRosenberg/ColorLab
BugReports: https://github.com/BoazRosenberg/ColorLab/issues
`,
  },
  {
    path: 'NAMESPACE',
    description: 'Exported R functions and imported dependencies',
    content: `# Generated by roxygen2: do not edit by hand

export(run_colorlab)
export(launch_palette_tutorial)
importFrom(learnr,run_tutorial)
importFrom(bslib,bs_theme)
importFrom(ggplot2,ggplot)
importFrom(colorspace,protan)
importFrom(colorspace,deutan)
importFrom(colorspace,tritan)
importFrom(colorspace,desaturate)
`,
  },
  {
    path: 'R/launch.R',
    description: 'Launch function to run the learnr tutorial inside RStudio Tutorial Pane',
    content: `#' Launch the ColorLab Tutorial in RStudio
#'
#' Launches the shiny_prerendered learnr tutorial optimized for the RStudio
#' Tutorial Pane. Once launched, it appears under the 'Tutorial' tab in RStudio
#' or opens in a standalone web browser window.
#'
#' @param ... Additional arguments forwarded to \\code{learnr::run_tutorial()}.
#' @return Runs the learnr interactive tutorial application.
#' @export
#' @examples
#' \\dontrun{
#' ColorLab::run_colorlab()
#' }
run_colorlab <- function(...) {
  learnr::run_tutorial("palette_designer", package = "ColorLab", ...)
}

#' @rdname run_colorlab
#' @export
launch_palette_tutorial <- function(...) {
  run_colorlab(...)
}
`,
  },
  {
    path: 'inst/tutorials/palette_designer/palette_designer.Rmd',
    description: 'The core learnr tutorial file (runtime: shiny_prerendered) formatted for RStudio',
    content: `---
title: "Interactive Palette & Shape Studio"
output:
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: "Interactive color palette and ggplot2 shape designer tailored for the RStudio Tutorial Pane."
---

\`\`\`{r setup, include=FALSE}
library(learnr)
library(shiny)
library(bslib)
library(ggplot2)
library(colorspace)

# Set knitr options
knitr::opts_chunk$set(echo = FALSE)

# Preset definitions
preset_list <- list(
  "Viridis (Sequential, CVD-Safe)" = list(
    colors = c("#440154", "#482878", "#3E4A89", "#31688E", "#26828E", "#1F9E89", "#35B779", "#6DCD59", "#B4DE2C", "#FDE725"),
    safe = TRUE,
    scale_col = "scale_color_viridis_d(option = 'viridis')",
    scale_fill = "scale_fill_viridis_d(option = 'viridis')"
  ),
  "Cividis (Sequential, Optimized CVD)" = list(
    colors = c("#00204D", "#1B315A", "#334467", "#4A5774", "#616A82", "#797F8F", "#92949D", "#ADACAC", "#CAC5BC", "#EAE5CC"),
    safe = TRUE,
    scale_col = "scale_color_viridis_d(option = 'cividis')",
    scale_fill = "scale_fill_viridis_d(option = 'cividis')"
  ),
  "Okabe-Ito (Categorical, Gold Standard)" = list(
    colors = c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000"),
    safe = TRUE,
    scale_col = 'scale_color_manual(values = c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000"))',
    scale_fill = 'scale_fill_manual(values = c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000"))'
  ),
  "RColorBrewer: Dark2" = list(
    colors = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D", "#666666"),
    safe = TRUE,
    scale_col = "scale_color_brewer(palette = 'Dark2')",
    scale_fill = "scale_fill_brewer(palette = 'Dark2')"
  ),
  "RColorBrewer: Set1" = list(
    colors = c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"),
    safe = FALSE,
    scale_col = "scale_color_brewer(palette = 'Set1')",
    scale_fill = "scale_fill_brewer(palette = 'Set1')"
  ),
  "RColorBrewer: Blues" = list(
    colors = c("#F7FBFF", "#DEEBF7", "#C6DBEF", "#9ECAE1", "#6BAED6", "#4292C6", "#2171B5", "#08519C", "#08306B"),
    safe = TRUE,
    scale_col = "scale_color_brewer(palette = 'Blues')",
    scale_fill = "scale_fill_brewer(palette = 'Blues')"
  )
)
\`\`\`

## Interactive Designer

Designed specifically for the compact dimensions of the RStudio Tutorial Pane.

\`\`\`{r studio_ui, echo=FALSE}
# UI optimized for narrow ~380px tutorial pane width
fluidPage(
  theme = bslib::bs_theme(version = 5, bg = "#FFFFFF", fg = "#0F172A", primary = "#2563EB"),
  
  # Collapsible Accessibility Bar
  div(
    style = "padding: 4px 8px; background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 6px; margin-bottom: 8px;",
    fluidRow(
      column(
        6,
        checkboxInput("cb_safe_only", label = tags$span(style="font-size:11px; font-weight:500;", "CVD Safe Only"), value = FALSE)
      ),
      column(
        6,
        selectInput(
          "cvd_mode",
          label = NULL,
          choices = c(
            "Vision: Normal" = "normal",
            "Protanopia" = "protan",
            "Deuteranopia" = "deutan",
            "Tritanopia" = "tritan",
            "Grayscale" = "grayscale"
          ),
          selected = "normal",
          width = "100%"
        )
      )
    )
  ),
  
  # Tab navigation
  tabsetPanel(
    id = "main_tabs",
    type = "pills",
    
    # Tab 1: Custom Palette (vector output default)
    tabPanel(
      "Custom",
      div(style = "padding-top: 6px;",
        div(
          style = "display: flex; gap: 4px; margin-bottom: 6px;",
          actionButton("add_swatch", "+ Add", class = "btn-sm btn-primary"),
          actionButton("delete_swatch", "Remove", class = "btn-sm btn-outline-secondary")
        ),
        uiOutput("custom_swatches_ui")
      )
    ),
    
    # Tab 2: Preset Palettes (Sub-tabs for Qualitative & Sequential, ggplot layer default)
    tabPanel(
      "Presets",
      div(style = "padding-top: 6px;",
        radioButtons("preset_type_sub", NULL, choices = c("Qualitative", "Sequential"), inline = TRUE),
        selectInput("preset_choice", "Palette:", choices = names(preset_list), width = "100%"),
        sliderInput("preset_n", "Colors (n):", min = 2, max = 10, value = 5, step = 1, width = "100%"),
        checkboxInput("enable_prune", "Edge Pruning", value = FALSE),
        conditionalPanel(
          condition = "input.enable_prune == true",
          sliderInput("trim_range", "Trim Cutoff (%):", min = 0, max = 100, value = c(0, 100), step = 5, width = "100%")
        ),
        actionButton("import_preset_to_custom", "Import to Custom", class = "btn-sm btn-dark w-100")
      )
    ),
    
    # Tab 3: Gradient Builder (Reorderable anchors, asymmetric steps)
    tabPanel(
      "Gradient",
      div(style = "padding-top: 6px;",
        fluidRow(
          column(6, colourpicker::colourInput("k1_col", "K1:", value = "#440154")),
          column(6, sliderInput("steps_k1_k2", "Steps to K2:", min = 1, max = 6, value = 2))
        ),
        fluidRow(
          column(6, colourpicker::colourInput("k2_col", "K2:", value = "#21908C")),
          column(6, sliderInput("steps_k2_k3", "Steps to K3:", min = 1, max = 6, value = 2))
        ),
        fluidRow(
          column(6, colourpicker::colourInput("k3_col", "K3:", value = "#FDE725"))
        ),
        actionButton("import_gradient_to_custom", "Import to Custom", class = "btn-sm btn-dark w-100")
      )
    ),
    
    # Tab 4: ggplot Shape Selector
    tabPanel(
      "Shapes",
      div(style = "padding-top: 6px;",
        selectInput("shape_preset", "Shape Combo:",
          choices = c(
            "Solid (16, 17, 15, 18)" = "solid",
            "Fillable (21, 22, 24, 25)" = "fillable",
            "Hollow (1, 2, 0, 5)" = "open"
          ),
          width = "100%"
        ),
        uiOutput("shapes_mapping_ui")
      )
    )
  ),
  
  hr(style="margin: 8px 0;"),
  
  # Live ggplot2 plot output (Clean white theme)
  plotOutput("live_preview_plot", height = "190px"),
  
  # Live R Code Generator (Minimal)
  div(
    style = "margin-top: 8px;",
    tags$div(style="font-size:11px; font-weight:600; color:#475569; margin-bottom:2px;", "R Code:"),
    verbatimTextOutput("live_r_code")
  )
)
\`\`\`

\`\`\`{r studio_server, context="server"}
# Reactive state for custom swatches
custom_colors <- reactiveVal(c("#1F77B4", "#FF7F0E", "#2CA02C"))

# Add swatch
observeEvent(input$add_swatch, {
  cols <- custom_colors()
  palette_pool <- c("#D62728", "#9467BD", "#8C564B", "#E377C2", "#7F7F7F", "#BCBD22", "#17BECF")
  next_col <- palette_pool[(length(cols) %% length(palette_pool)) + 1]
  custom_colors(c(cols, next_col))
})

# Remove swatch
observeEvent(input$delete_swatch, {
  cols <- custom_colors()
  if (length(cols) > 1) {
    custom_colors(cols[-length(cols)])
  }
})

# Dynamic custom swatches UI
output$custom_swatches_ui <- renderUI({
  cols <- custom_colors()
  lapply(seq_along(cols), function(i) {
    fluidRow(
      style = "margin-bottom: 4px;",
      column(4, textInput(paste0("swatch_label_", i), label = NULL, value = paste0("var_", i), placeholder = "label")),
      column(8, colourpicker::colourInput(paste0("swatch_val_", i), label = NULL, value = cols[i]))
    )
  })
})

# Transform colors based on CVD selection using colorspace
sim_colors <- function(cols, mode) {
  if (mode == "protan") return(colorspace::protan(cols))
  if (mode == "deutan") return(colorspace::deutan(cols))
  if (mode == "tritan") return(colorspace::tritan(cols))
  if (mode == "grayscale") return(colorspace::desaturate(cols))
  return(cols)
}

# Live Plot Output
output$live_preview_plot <- renderPlot({
  tab <- input$main_tabs
  cvd <- input$cvd_mode
  
  if (tab == "4. Shapes") {
    # Shape scatter plot
    pchs <- switch(input$shape_preset,
      "solid" = c(16, 17, 15, 18),
      "fillable" = c(21, 22, 24, 25),
      "open" = c(1, 2, 0, 5),
      c(16, 3, 17, 4)
    )
    cols <- sim_colors(custom_colors()[1:length(pchs)], cvd)
    
    df <- iris[1:60, ]
    df$Species <- factor(rep(paste("Class", 1:length(pchs)), length.out = nrow(df)))
    
    p <- ggplot(df, aes(x = Sepal.Length, y = Sepal.Width, color = Species, shape = Species)) +
      geom_point(size = 3.5, stroke = 1.2) +
      scale_shape_manual(values = pchs) +
      scale_color_manual(values = cols) +
      theme_minimal() +
      labs(title = paste("Point Scale Preview (CVD:", cvd, ")"))
    return(p)
  }
  
  # Standard color palette preview
  cols <- sim_colors(custom_colors(), cvd)
  df <- data.frame(
    Category = factor(paste("Group", seq_along(cols)), levels = paste("Group", seq_along(cols))),
    Value = seq(10, by = 5, length.out = length(cols))
  )
  
  ggplot(df, aes(x = Category, y = Value, fill = Category)) +
    geom_col(width = 0.6) +
    scale_fill_manual(values = cols) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
    labs(title = paste("Palette Preview (CVD:", cvd, ")"), y = "Value", x = NULL)
})

# Live R Code Generator
output$live_r_code <- renderText({
  cols <- custom_colors()
  vec_str <- paste0('c("', paste(cols, collapse = '", "'), '")')
  
  paste0(
    "# Generated production ggplot2 scale\\n",
    "my_colors <- ", vec_str, "\\n\\n",
    "scale_color_manual(values = my_colors)\\n",
    "# or for fill:\\n",
    "scale_fill_manual(values = my_colors)"
  )
})
\`\`\`

## Interactive Practice Exercise

Test your generated palette with this real R code execution chunk!

\`\`\`{r practice_palette, exercise=TRUE}
# Edit the code below using your generated palette:
my_palette <- c("#1F77B4", "#FF7F0E", "#2CA02C")

ggplot(iris, aes(x = Petal.Length, y = Petal.Width, color = Species)) +
  geom_point(size = 3) +
  scale_color_manual(values = my_palette) +
  theme_minimal() +
  labs(title = "Iris Species with Custom Palette")
\`\`\`
`,
  },
  {
    path: 'README.md',
    description: 'Package documentation and RStudio Tutorial Pane installation instructions',
    content: `# ColorLab 🎨

Interactive Color & Shape Palette Designer for ggplot2 and RStudio.

## Installation

\`\`\`r
# Install from GitHub
remotes::install_github("BoazRosenberg/ColorLab")

# Or with pak
pak::pak("BoazRosenberg/ColorLab")
\`\`\`

## Launching in RStudio

### 1. In RStudio Tutorial Pane (Recommended)
Open RStudio, click the **Tutorial** tab in the top-right pane, and select **"Interactive Palette & Shape Studio"**!

### 2. From R Console
\`\`\`r
library(ColorLab)
run_colorlab()
\`\`\`
`,
  },
  {
    path: 'tests/testthat/test-palette.R',
    description: 'Unit tests verifying tutorial existence and package launch',
    content: `test_that("palette_designer tutorial exists in package", {
  tutorials <- learnr::available_tutorials("ColorLab")
  expect_true("palette_designer" %in% tutorials$name)
})
`,
  },
];

/**
 * Creates and downloads the complete R package as a zip archive using JSZip.
 */
export async function downloadRPackageZip(): Promise<void> {
  const zip = new JSZip();
  const rootFolder = zip.folder('ColorLab');

  if (!rootFolder) {
    throw new Error('Failed to create zip root folder');
  }

  // Add all files
  for (const file of R_PACKAGE_FILES) {
    rootFolder.file(file.path, file.content);
  }

  const content = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(content);
  const link = document.createElement('a');
  link.href = url;
  link.download = 'ColorLab_0.1.0.zip';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
