import { BaseThemeName, ThemeSettings } from '../types/palette';

export const BASE_THEMES: Array<{
  id: BaseThemeName;
  name: string;
  rFunction: string;
  description: string;
  settings: Partial<ThemeSettings>;
}> = [
  {
    id: 'minimal',
    name: 'Minimal',
    rFunction: 'theme_minimal',
    description: 'A minimalistic theme with no background annotations',
    settings: {
      plotBackground: '#FFFFFF',
      panelBackground: '#FFFFFF',
      hasPanelBorder: false,
      hasAxisLine: false,
      showMajorGrid: true,
      majorGridColor: '#F1F5F9',
      majorGridLinetype: 'solid',
      showMinorGrid: true,
      minorGridColor: '#F8FAFC',
      showTicks: false,
      ticksColor: '#94A3B8',
      facetStripBackground: '#E2E8F0',
      facetStripTextColor: '#1E293B',
      facetStripTextBold: true,
      facetStripBorder: false,
      legendPosition: 'right',
    },
  },
  {
    id: 'classic',
    name: 'Classic',
    rFunction: 'theme_classic',
    description: 'Classic theme with x & y axis lines and no gridlines',
    settings: {
      plotBackground: '#FFFFFF',
      panelBackground: '#FFFFFF',
      hasPanelBorder: false,
      hasAxisLine: true,
      axisLineColor: '#0F172A',
      showMajorGrid: false,
      showMinorGrid: false,
      showTicks: true,
      ticksColor: '#0F172A',
      facetStripBackground: '#E2E8F0',
      facetStripTextColor: '#0F172A',
      facetStripTextBold: true,
      facetStripBorder: true,
      legendPosition: 'right',
    },
  },
  {
    id: 'bw',
    name: 'B&W',
    rFunction: 'theme_bw',
    description: 'Black and white theme with a full panel border',
    settings: {
      plotBackground: '#FFFFFF',
      panelBackground: '#FFFFFF',
      hasPanelBorder: true,
      panelBorderColor: '#0F172A',
      hasAxisLine: false,
      showMajorGrid: true,
      majorGridColor: '#E2E8F0',
      majorGridLinetype: 'solid',
      showMinorGrid: true,
      minorGridColor: '#F1F5F9',
      showTicks: true,
      ticksColor: '#0F172A',
      facetStripBackground: '#CBD5E1',
      facetStripTextColor: '#0F172A',
      facetStripTextBold: true,
      facetStripBorder: true,
      legendPosition: 'right',
    },
  },
  {
    id: 'light',
    name: 'Light',
    rFunction: 'theme_light',
    description: 'Light gray border and subtle gridlines',
    settings: {
      plotBackground: '#FFFFFF',
      panelBackground: '#FFFFFF',
      hasPanelBorder: true,
      panelBorderColor: '#CBD5E1',
      hasAxisLine: false,
      showMajorGrid: true,
      majorGridColor: '#F1F5F9',
      majorGridLinetype: 'solid',
      showMinorGrid: true,
      minorGridColor: '#F8FAFC',
      showTicks: true,
      ticksColor: '#94A3B8',
      facetStripBackground: '#E2E8F0',
      facetStripTextColor: '#1E293B',
      facetStripTextBold: true,
      facetStripBorder: true,
      legendPosition: 'right',
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    rFunction: 'theme_dark',
    description: 'Dark panel for high contrast illuminated geometries',
    settings: {
      plotBackground: '#0F172A',
      panelBackground: '#1E293B',
      hasPanelBorder: false,
      hasAxisLine: false,
      showMajorGrid: true,
      majorGridColor: '#334155',
      majorGridLinetype: 'solid',
      showMinorGrid: true,
      minorGridColor: '#1E293B',
      showTicks: false,
      ticksColor: '#64748B',
      facetStripBackground: '#334155',
      facetStripTextColor: '#F8FAFC',
      facetStripTextBold: true,
      facetStripBorder: false,
      legendPosition: 'right',
    },
  },
  {
    id: 'gray',
    name: 'Gray',
    rFunction: 'theme_gray',
    description: 'Default ggplot2 signature signature gray canvas',
    settings: {
      plotBackground: '#FFFFFF',
      panelBackground: '#EBEBEB',
      hasPanelBorder: false,
      hasAxisLine: false,
      showMajorGrid: true,
      majorGridColor: '#FFFFFF',
      majorGridLinetype: 'solid',
      showMinorGrid: true,
      minorGridColor: '#FFFFFF',
      showTicks: true,
      ticksColor: '#333333',
      facetStripBackground: '#D9D9D9',
      facetStripTextColor: '#1A1A1A',
      facetStripTextBold: true,
      facetStripBorder: false,
      legendPosition: 'right',
    },
  },
  {
    id: 'void',
    name: 'Void',
    rFunction: 'theme_void',
    description: 'Completely empty theme ideal for maps, diagrams, or networks',
    settings: {
      plotBackground: '#FFFFFF',
      panelBackground: '#FFFFFF',
      hasPanelBorder: false,
      hasAxisLine: false,
      showMajorGrid: false,
      showMinorGrid: false,
      showTicks: false,
      legendPosition: 'none',
    },
  },
];

export const DEFAULT_THEME_SETTINGS: ThemeSettings = {
  baseTheme: 'minimal',
  baseSize: 11,
  fontFamily: 'sans',
  titleFace: 'bold',

  isTransparentBackground: false,
  plotBackground: '#FFFFFF',
  panelBackground: '#FFFFFF',
  hasPanelBorder: false,
  panelBorderColor: '#0F172A',
  hasAxisLine: false,
  axisLineColor: '#0F172A',

  showMajorGrid: true,
  majorGridColor: '#F1F5F9',
  majorGridLinetype: 'solid',
  showMinorGrid: true,
  minorGridColor: '#F8FAFC',
  showTicks: false,
  ticksColor: '#94A3B8',
  scaleFormatting: 'normal',

  facetStripBackground: '#E2E8F0',
  isFacetStripTransparent: false,
  facetStripTextColor: '#1E293B',
  facetStripTextBold: true,
  facetStripBorder: false,
  facet1Name: 'Group A',
  facet2Name: 'Group B',

  legendPosition: 'right',
  isLegendTransparent: true,
  legendBackground: '#FFFFFF',
};
